### ISSUE TITLE
Error: chipsec.modules.biosguard/common.bios_wp/common.igd_xref/common.spi_access

### ISSUE THREAD

**Issue by JuanLJ63** [chipsec/chipsec#2076] opened 2024-03-11 08:06 UTC
Hi all,

I have some exception raised during the followinf chipsec modules execution.
Can you help me undertand these errors and how it can be fixed ?

Here is my configuration:

OS: Windows 11 Pro(22631.3155)
chipsec version used : 1.12.9
CPU: Intel(R) Core(TM) Ultra 7 155U

Thank you !

[CHIPSEC] Modules with exceptions 4:
ERROR: chipsec.modules.biosguard
ERROR: chipsec.modules.common.bios_wp
ERROR: chipsec.modules.common.igd_xref
ERROR: chipsec.modules.common.spi_access
[chipsec_secureboot_disable.log](https://github.com/chipsec/chipsec/files/14555329/chipsec_secureboot_disable.log)

**Comment by npmitche** [comment] 2024-03-11 22:52
The issue is we don't have a configuration yet for MTL. We'll put it in the queue to get it done, but if anyone else wants to create the xml, you are welcome to!

**Comment by npmitche** [comment] 2024-09-03 16:41
Fixed with https://github.com/chipsec/chipsec/pull/2174

**Closed as completed by npmitche** 2024-09-03 16:41 UTC
Labels: good first issue, help wanted, configuration
